# Generated by Django 4.1 on 2023-05-05 00:01

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="noisedata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row_id", models.IntegerField(max_length=200)),
                ("lamax", models.DecimalField(decimal_places=25, max_digits=50)),
                ("laeq", models.DecimalField(decimal_places=25, max_digits=50)),
                ("lceq", models.DecimalField(decimal_places=25, max_digits=50)),
                ("lcpeak", models.DecimalField(decimal_places=25, max_digits=50)),
                ("description", models.CharField(max_length=200)),
                ("number_of_events", models.IntegerField()),
                ("year", models.IntegerField()),
                ("month", models.IntegerField()),
                ("day", models.IntegerField()),
                ("date", models.DateField()),
                ("hour", models.TimeField()),
                ("hour_of_year", models.IntegerField()),
                ("lc_humidity", models.DecimalField(decimal_places=25, max_digits=50)),
                ("lc_dwptemp", models.DecimalField(decimal_places=25, max_digits=50)),
                ("lc_rad", models.DecimalField(decimal_places=25, max_digits=50)),
                ("lc_rainin", models.DecimalField(decimal_places=25, max_digits=50)),
                ("lc_winddir", models.DecimalField(decimal_places=25, max_digits=50)),
                ("lc_windspeed", models.DecimalField(decimal_places=25, max_digits=50)),
                ("lc_temp", models.DecimalField(decimal_places=25, max_digits=50)),
            ],
        ),
    ]
