# Generated by Django 4.1 on 2023-05-05 00:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("noiseDataRestApi", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="noisedata",
            name="date",
        ),
        migrations.AlterField(
            model_name="noisedata",
            name="row_id",
            field=models.IntegerField(),
        ),
    ]
