# Generated by Django 4.1 on 2023-05-05 21:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("noiseDataRestApi", "0002_remove_noisedata_date_alter_noisedata_row_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="noiseLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=200)),
                ("type", models.CharField(max_length=200)),
                (
                    "coordinates_longitude",
                    models.DecimalField(decimal_places=25, max_digits=50),
                ),
                (
                    "coordinates_lattitude",
                    models.DecimalField(decimal_places=25, max_digits=50),
                ),
            ],
        ),
    ]
