# Generated by Django 4.1 on 2023-05-05 21:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("noiseDataRestApi", "0003_noiselocation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="noiselocation",
            name="coordinates_lattitude",
            field=models.DecimalField(decimal_places=40, max_digits=50),
        ),
        migrations.AlterField(
            model_name="noiselocation",
            name="coordinates_longitude",
            field=models.DecimalField(decimal_places=40, max_digits=50),
        ),
    ]
