# Generated by Django 4.1 on 2023-05-05 21:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("noiseDataRestApi", "0004_alter_noiselocation_coordinates_lattitude_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="noiselocation",
            name="coordinates_lattitude",
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name="noiselocation",
            name="coordinates_longitude",
            field=models.CharField(max_length=400),
        ),
    ]
